// Bloom test shader

uniform sampler2D tex;

void VertexShaderMain()
{
	gl_TexCoord[0] = gl_MultiTexCoord0;
	gl_Position    = ftransform();
}


void PixelShaderMain()
{
	vec3 c;
	vec2 TexCoord = gl_TexCoord[0].st;
	c = texture2D(tex, TexCoord).rgb;
#if 1
	float m = max(c.r, c.g);
	m = max(m, c.b);
	if (m < 1.0) c = vec3(0.0);
	c *= 0.5;
#else
	c = (c - vec3(1.0)) * 20.0;
#endif
	gl_FragColor = vec4(c, 1.0);
}
